src/Entity/Employer.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EmployerRepository")
 */
class Employer
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $matricule;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $age;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Service", inversedBy="employers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_service;

    /**
     * @ORM\Column(type="integer")
     */
    private $salaire;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMatricule(): ?string
    {
        return $this->matricule;
    }

    public function setMatricule(string $matricule): self
    {
        $this->matricule = $matricule;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAge(): ?string
    {
        return $this->age;
    }

    public function setAge(string $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getIdService(): ?Service
    {
        return $this->id_service;
    }

    public function setIdService(?Service $id_service): self
    {
        $this->id_service = $id_service;

        return $this;
    }

    public function getSalaire(): ?int
    {
        return $this->salaire;
    }

    public function setSalaire(int $salaire): self
    {
        $this->salaire = $salaire;

        return $this;
    }
}

src/Entity/Service.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ServiceRepository")
 */
class Service
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Employer", mappedBy="id_service")
     */
    private $employers;

    public function __construct()
    {
        $this->employers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    /**
     * @return Collection|Employer[]
     */
    public function getEmployers(): Collection
    {
        return $this->employers;
    }

    public function addEmployer(Employer $employer): self
    {
        if (!$this->employers->contains($employer)) {
            $this->employers[] = $employer;
            $employer->setIdService($this);
        }

        return $this;
    }

    public function removeEmployer(Employer $employer): self
    {
        if ($this->employers->contains($employer)) {
            $this->employers->removeElement($employer);
            // set the owning side to null (unless already changed)
            if ($employer->getIdService() === $this) {
                $employer->setIdService(null);
            }
        }

        return $this;
    }
}

src/Form/EmployerType.php
<?php

namespace App\Form;

use App\Entity\Employer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmployerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('matricule')
            ->add('nom')
            ->add('prenom')
            ->add('age')
            ->add('service')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Employer::class,
        ]);
    }
}

src/Controller/EmployerController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use App\Entity\Employer;
use App\Entity\Service;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;


class EmployerController extends AbstractController
{
       /**
     * @Route("home", name="home")
     */
    public function home()
    {
        return $this->render('employer/home.html.twig', [
            'controller_name' => 'EmployerController',
        ]);
    }
       /**
     * @Route("/employer", name="lister")
     */
    public function lister(){
        $employer=$this->getDoctrine()->getRepository(Employer::class)->findAll();
        return $this->render('employer/lister.html.twig',[
            'employer' =>$employer,
        ]);
    }
    
      /**
     * @Route("/ajout",name="employer_create")
     * @Route("/employer/{id}/ajout", name="employer_edit")
     */
    public function form(Employer $employer=null,Request $request, ObjectManager $manager){
        if(!$employer){
            $employer= new Employer;
       }
          $form = $this->createFormBuilder($employer);
            $form->add('matricule');
            $form->add('nom');
            $form->add('prenom');
            $form->add('age');
            $form->add('id_service',EntityType::class,[
                'class'=> Service::class,
                'choice_label'=> 'libelle'
            ]);
            $form->add('salaire');
            $form=$form->getForm();
            $form->handleRequest($request);
                if($form->isSubmitted() && $form->isValid()){
                   $manager->persist($employer);
                    $manager->flush();
                    return $this->redirectToroute('lister');
            }
                    return $this->render('add.html.twig',[
                    'formEmployer' =>$form->createView(),'editMode'=>$employer->getId() ==!null
        ]);
    
   

    }
     /**
     * @Route("/employer/{id}/supprimer", name="employer-edit")
     */
    public function Supprimeremployer(Employer $employer,ObjectManager $manager){
            $manager->remove($employer);
            $manager->flush();
            return $this->redirectToroute('lister');
    }


     /**
     * @Route("/employer/service", name="listerservice")
     */
    public function listerService(){
        $service=$this->getDoctrine()->getRepository(Service::class)->findAll();
        return $this->render('employer/listerservice.html.twig',[
            'services' =>$service,
        ]);
    }
    
  
    /**
     * @Route("employer/ajoutservice",name="service-create")
     */

    public function formService(Service $service=null,Request $request, ObjectManager $manager){
        if(!$service){
            $service= new Service;
       }
          $form = $this->createFormBuilder($service);
            $form->add('libelle');
            $form=$form->getForm();
            $form->handleRequest($request);
                if($form->isSubmitted() && $form->isValid()){
                   $manager->persist($service);
                    $manager->flush();
                    return $this->redirectToroute('listerservice');
            }
                    return $this->render('employer/addservice.html.twig',[
                    'formService' =>$form->createView()
        ]);
    
   }
     
  
    
  
}

templates/add.html.twig
{% extends 'base.html.twig' %}
{% form_theme formEmployer 'bootstrap_4_layout.html.twig' %}
{% block body %}

<h1> AJOUTEZ UN EMPLOYER</h1>
   
    
    {{form_start(formEmployer)}}

    {{ form_row(formEmployer.matricule,{'attr':{'placeholder':"matricule"}})}}
    {{ form_row(formEmployer.nom,{'attr':{'placeholder':"nom"}})}}
    {{ form_row(formEmployer.prenom,{'attr':{'placeholder':"prenom"}})}}
    {{ form_row(formEmployer.age,{'attr':{'placeholder':"age"}})}}
    {{ form_row(formEmployer.salaire,{'attr':{'placeholder':"salaire"}})}}
    {{ form_row(formEmployer.id_service,{'attr':{'placeholder':"service"}})}}

    <button type="submit" class="btn btn-success">

        {% if editMode %}
            Modifier 
            {% else %} 
            Ajouter
         {% endif %} 

    </button>
   
    {{form_end(formEmployer)}}
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://bootswatch.com/4/flatly/bootstrap.min.css">
        {% block stylesheets %}{% endblock %}
    </head>
  <body>
            <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
              <a class="navbar-brand" href="">GESTION DES SERVICES</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                  
                    <a class="nav-link" href="/employer">NOS EMPLOYERS</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{path('employer_create')}}">AJOUTER UN EMPLOYER</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="/employer/service">NOS SERVICES</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="/employer/ajoutservice">AJOUTER SERVICE</a>
                    </li>
                 
                </ul>
              
              </div>
            </nav>
      <div class="container">
        {% block body %}{% endblock %}
    </div>
    {% block javascripts %}{% endblock %}
</body>
</html>

templates/employer/addservice.html.twig
{% extends 'base.html.twig' %}
{% form_theme formService 'bootstrap_4_layout.html.twig' %}
{% block body %}

<h1> AJOUTEZ UNE SERVICE</h1>
   
    
    {{form_start(formService)}}

    {{ form_row(formService.libelle,{'attr':{'placeholder':"libelle"}})}}
  

    <button type="submit" class="btn btn-success">Ajouter</button>
   
    {{form(formService)}}
{% endblock %}

templates/employer/home.html.twig
{% extends 'base.html.twig'%}
{% block body%}
                <h1>bienvenu</h1>

{% endblock %}

templates/employer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EmployerController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>
    This friendly message is coming from:
    <ul>
    
        <li>Your controller at <code><a href="{{ '/home/aminata/employer/src/Controller/EmployerController.php'|file_link(0) }}">src/Controller/EmployerController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/home/aminata/employer/templates/employer/index.html.twig'|file_link(0) }}">templates/employer/index.html.twig</a></code></li>
    </ul>

</div>
{% endblock %}

templates/employer/lister.html.twig
 {% extends "base.html.twig" %}
 {% block title %}LISTES DES EMPLOYERS{% endblock %}

 {% block body %}
 {% if employer %}
 <table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>matricule</th>
            <th>nom</th>
            <th>Prenom</th>
            <th>Age</th>
            <th>salaire</th>
            <th>libelle</th>
            <th></th>
            <th></th>
        </tr
    </thead>
    <tbody>
        <tr>
        {% for employer in employer %}
            <td>{{employer.matricule}}</td>
            <td>{{employer.nom}}</td>
            <td>{{employer.prenom}}</td>
            <td>{{employer.age}}</td>
            <td>{{employer.salaire}}</td>
            <td>{{employer.idService.libelle}}</td>
            <td>
            <button class="btn btn-danger">
                <a href="/employer/{{employer.id}}/supprimer">SUPPRIMER</a>
                </button>
                </td>
                <td>
                <button class="btn btn-primary">
                <a href="/employer/{{employer.id}}/ajout">MODIFIER</a>
                </button>
                </td>
             
        </tr>
     
  {% endfor %} 
  {% endif %} 
     
 {% endblock  %}

templates/employer/listerservice.html.twig
{% extends "base.html.twig" %}
 {% block title %}LISTES DES EMPLOYERS{% endblock %}

 {% block body %}
<table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>service</th>
            </tr>
    </thead>
    <tbody>
        <tr>
            
        {% for service in services %}
            <td>{{service.libelle}}</td>
        </tr>
        {% endfor %} 
        </tbody> 
         </table> 
{% endblock  %}